/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gdemo.app;

import gdemo.list.LinkedList;

import static gdemo.utilities.StringUtils.join;
import static gdemo.utilities.StringUtils.split;

import java.io.File;
import java.io.IOException;

import static gdemo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
        
		System.out.println(Common.logo);
		DataContainer dataContainer = new DataContainer();
		dataContainer.setSourceFiles(Common.listDir(Common.sourcePath));
		System.out.println(dataContainer.getSourceFiles());

		ToCSV toCSV = new ToCSV();
		
		for (File sourceFile : dataContainer.getSourceFiles()) {
			try {
				toCSV.convertExcelToCSV(sourceFile.getAbsolutePath(),
						Common.targetPath.getAbsolutePath());
			} catch (IllegalArgumentException | IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}			
		}

		CompareHeader compareHeader = new CompareHeader();
		for (File sourceFile : dataContainer.getSourceFiles()) {
			try {
				compareHeader.compareHeaderToCSV(sourceFile.getAbsolutePath(),
						Common.targetPath.getAbsolutePath() + File.separator + "compareResult.csv");
			} catch (IllegalArgumentException | IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}			
		}
		
		
    }
}
